name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./app.py # Specify your bot's directory

      - name: Run the bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          python app.py
        working-directory: ./app.py
